### ISSUE TITLE
Scope of the quick start should be determined

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/website#4]
The quick start was condensed from a multi-page section to the one-page we have now to address concerns that it was too long.  Also addressing non-compute users and condo users should be considered.

I suppose we either need to nuance the quick start for all types of users or generate multiple quick starts (Compute, storage, condo, class,UCD, NCAR, ?) or try to scope the quick start to only cover getting an account and logging in (or connecting with a file transfer app).

Condo users do not need an allocation, class users are provided with one, both should not initially be encouraged to get a Startup as that is then wasted and just confuses their default.  Many users are likely unsure of what type of user they are.

Monte had proposed a forking path where the user selects their needs and is led through the quick-start.  I believe rather than just links to sub-pages it was expected to have some sort of embedded elements which are revealed.  It is unclear how multiple overlapping cases were to be handled, I suppose a landing page could be created for all cases.  I recall this idea was well-received as a way to address the problem.  It sounds like it would be a challenge to integrate into the Drupal Book so it might be a nonstarter.  If we just nuance the quick start it will be a bit cumbersome but maybe that is unavoidable.

Personally I (Joel) would carve out anything beyond logging in and requesting your needs from the quick start as it quickly becomes a challenge to cover what is needed at the correct audience level.
Submitting a job is irrelevant to storage users and class/condo users will probably get specifics from their internal docs.  What they need to do is:
Compute - Request an allocation (or access to one) and learn about the resources.
Storage - Get their PI to request access for them via the relevant group
Condo - Follow their internal docs, get Kai to request ICS group and allocation access, etc.
Class - go to class, pay attention.
UCD - These users generally get handled via email after the initial allocation request and may never follow our current Quick Start, I do not know if that should change.  Perhaps once I have had one request an allocation.
NCAR - generally they follow the CISL docs and if they come in through www.rc they get scraped off by the account request portal.  We can refer to them in our Quick Start and refer them to CISL or just write the Quick Start for an audience that does not include them at all.

**Comment by anderbubble** [comment]
I think audience-specific quick-starts is the way to go. I even think we might want to publish those entirely separately from the rest of the user guide.

**Comment by anderbubble** [comment]
Progress of implementation is being tracked in #60.
