### ISSUE TITLE
double-wide outlines are ugly

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/website#61]
The current h2-extracting outline plugin nests page outlines within the page body; but this is really ugly when there's already a site outline block outside the page body.

Example: https://www-test.rc.colorado.edu/support/user-guide/remote-access.html

We should get the page outlines to be in-line with the site outline; probably above. It'd be good if they looked the same as the site outlines, too.

**Comment by anderbubble** [comment]
If this isn't possible, even just not floating the page outline to the right would make it better.

**Comment by beckyyeager** [comment]
Changed layout and design of table of contents module. Can be adjusted again if others have suggestions
