### ISSUE TITLE
fix Drupal's handling of <code> tags

### ISSUE THREAD

**Issue by anderbubble** [ResearchComputing/website#8]
Drupal is mangling `<code>` tags on two fronts: Prettify breaks when `<code>` tags contain hyperlinks; and the current theme makes all `<code>` tags block-level elements with very specific formatting.

I recommend the following `<style>` tag, which can be placed at the top of the Drupal page, until we can actually fix Drupal:

    <style type="text/css">
    :not(pre) > code
    {
      display: inline;
      background-color: inherit;
      border: none;
      margin: 0;
      padding: 0;
      line-height: normal;
      overflow: inherit;
      font-size: inherit;
    }
    </style>

**Comment by anderbubble** [comment]
I've disabled prettify entirely for now, as I was not able to reliably disable it on specific elements.

**Comment by anderbubble** [comment]
Becky,

I'm giving this to you for now, simply because I don't know how to change the Drupal CSS. If you can tell me how to change it, I'm happy to integrate this change myself.

~jonathon

**Comment by beckyyeager** [comment]
Added to style.css under Drupal theme

**Comment by anderbubble** [comment]
Saw this still happening at `getting-started/petalibrary.html`
