### ISSUE TITLE
Errors on page in response to a search

### ISSUE THREAD

**Issue by jafrahm** [ResearchComputing/website#89]
I searched the site with keyword "class" to see if the new page was up, and the results page had the error copied below:

-----
Error message
Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Unexpected end tag : p in Entity, line: 10 in simple_table_of_contents_generate_table_of_contents() (line 108 of /data/web/htdocs/www/sites/all/modules/simple_table_of_contents/simple_table_of_contents.module).
Warning: DOMDocument::loadHTML() [domdocument.loadhtml]: Unexpected end tag : p in Entity, line: 19 in simple_table_of_contents_generate_table_of_contents() (line 108 of /data/web/htdocs/www/sites/all/modules/simple_table_of_contents/simple_table_of_contents.module).
You are here
Home»Search»Content»Search
Search
Enter your keywords

class
----

**Comment by beckyyeager** [comment]
The errors have been fixed. We just need to figure out where to put the page.
